### ISSUE TITLE
Open a new tab/ window when the link is an external link + opposite

### ISSUE THREAD

**Issue by TabeaHe** [Blueshoe/website#101]
Could you please check if it is possible to open a new tab/ window when the link is an external link?

**Comment by TabeaHe** [comment]
https://26-12-3.website-de.pages.dev/leistungen/migration-auf-kubernetes/
Here is still an external link opening in the same tab: 

![Image](https://github.com/Blueshoe/website/assets/106660869/5234efaa-d41e-485c-9761-b27d5ad6832f)

**Comment by TabeaHe** [comment]
https://26-12-4.blueshoe-io.pages.dev/our-services/cloud-application-development

This still opens in anew tab:
![Image](https://github.com/Blueshoe/website/assets/106660869/8b027acf-3724-4706-bf5c-e439e1d179b5)

**Comment by MaksymOsovitnii** [comment]
@TabeaHe , fixed, you can check it here https://30-12.blueshoe-io.pages.dev/our-services/cloud-application-development
