### ISSUE TITLE
Anchor

### ISSUE THREAD

**Issue by TabeaHe** [Blueshoe/website#105]
https://24-12.website-de.pages.dev/leistungen/workflow-automatisierung
When clicking on one of the articles and then clicking back, I arrive at the beginning of the page and not at the articles. Could you please fix that?
![image](https://github.com/Blueshoe/website/assets/106660869/a7aa3765-4a99-4468-ba91-46ac136b94d3)

Here it's the same: https://24-12.website-de.pages.dev/leistungen/microservice-architektur-beratung/

and here: https://24-12.website-de.pages.dev/leistungen/cloud-infrastruktur-beratung

and here: https://24-12.website-de.pages.dev/leistungen/cloud-native-tools

**Comment by TabeaHe** [comment]
@MaksymOsovitnii it just works on (https://26-12-3.website-de.pages.dev/leistungen/microservice-architektur-beratung) For the other links the issue is the same

**Comment by MaksymOsovitnii** [comment]
@TabeaHe , it is because the posts are on the other website (english version), when you will replace them with DE posts scroll position will be restored after clicking back button
