### ISSUE TITLE
gtag missing on blueshoe.de

### ISSUE THREAD

**Issue by Truthans** [Blueshoe/website#120]
Hey @MaksymOsovitnii,

it looks like the gtag on blueshoe.de is missing. Blueshoe.io is working though. Here is the code, could you put it in the head section?:

<script async src="https://www.googletagmanager.com/gtag/js?id=G-MNZQV3V3KS"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-MNZQV3V3KS');
</script>

**Comment by MaksymOsovitnii** [comment]
@Truthans , please, check. I have merged this fix to main.

**Comment by Truthans** [comment]
@MaksymOsovitnii I am currently getting this, when I go to the "blueshoe.de" page:

![Bildschirm­foto 2024-02-20 um 09 54 33](https://github.com/Blueshoe/website/assets/5262921/1e0ee088-164e-40ae-9006-aec1afb780ab)

**Comment by MaksymOsovitnii** [comment]
@Truthans , please. check. And sorry for the broken deploy. I will not repeat this.
