### ISSUE TITLE
Sitemap

### ISSUE THREAD

**Issue by TabeaHe** [Blueshoe/website#122]
Could you please update the sitemap? 
![issues-sitemap](https://github.com/Blueshoe/website/assets/106660869/e80ef892-a7b0-455f-b0af-b99c218f2329)

**Comment by MaksymOsovitnii** [comment]
@TabeaHe , here it is and it has these links: https://www.blueshoe.io/sitemap.xml

**Comment by TabeaHe** [comment]
@MaksymOsovitnii There are still URLs which are not on the website:
<url>
<loc>https://www.blueshoe.io/projects/deutsches-museum</loc>
<changefreq>monthly</changefreq>
</url>
<url>
<loc>https://www.blueshoe.io/projects/dom-perignon-shopping-window</loc>
<changefreq>monthly</changefreq>
</url>
<url>
<loc>https://www.blueshoe.io/projects/liefer-app-prototyp</loc>
<changefreq>monthly</changefreq>
</url>
<url>
<loc>https://www.blueshoe.io/projects/loyalty-engine</loc>
<changefreq>monthly</changefreq>
</url>
<url>
<loc>https://www.blueshoe.io/projects/multistore-e-commerce</loc>
<changefreq>monthly</changefreq>
</url>
<url>
<loc>https://www.blueshoe.io/projects/partnermanagement-plattform-allgaeu</loc>
<changefreq>monthly</changefreq>
</url>

**Comment by TabeaHe** [comment]
Does the sitemap update automatically in the future?

**Comment by MaksymOsovitnii** [comment]
@TabeaHe , I will check and fix it today. Yes, it updates automatically.

**Comment by MaksymOsovitnii** [comment]
@TabeaHe , please, check, all these pages exists (you asked me to create for future, but hide them). For example you can visit this page (one from the issue described by you) https://www.blueshoe.io/projects/deutsches-museum, but it is not available in navigation on the website, so users will not enter it. Now there will be no 404 error

**Comment by TabeaHe** [comment]
@MaksymOsovitnii I wasn't aware that they'd appear in the sitemap. Okay, thank's a lot for double checking and the explanation.

**Comment by MaksymOsovitnii** [comment]
@TabeaHe , if you want Ican delete them for now from website, or from the site map only. As you wish

**Comment by TabeaHe** [comment]
@MaksymOsovitnii you can leave them in the sitemap. We'll translate them soon and then everything is fine.
