### ISSUE TITLE
open graph data

### ISSUE THREAD

**Issue by TabeaHe** [Blueshoe/website#130]
How and where can we adapt the open graph data? Could you set open graph data on each page per default and we adapt it step by step?

**Comment by MaksymOsovitnii** [comment]
@TabeaHe , sure. Just give me a standard list (default one). I can place it on each page, show you where it is and then you can adapt step by step. This works?

**Comment by TabeaHe** [comment]
@MaksymOsovitnii You would need title, description and image. Is that correct?

**Comment by MaksymOsovitnii** [comment]
@TabeaHe Yes

**Comment by TabeaHe** [comment]
@MaksymOsovitnii I'll come back to you tomorrow

**Comment by MaksymOsovitnii** [comment]
@TabeaHe , I will be waiting for your decision! Thanks

**Comment by TabeaHe** [comment]
@MaksymOsovitnii Could you take the title and description from each single page for the open graph data? I would provide you with a picture tomorrow that you could use on all pages and that we could adapt step by step.

**Comment by TabeaHe** [comment]
@MaksymOsovitnii I added the picture here:https://github.com/Blueshoe/website-de/blob/master/public/img/open%20graph/Blueshoe-cloud-native-devlopment.png

**Comment by MaksymOsovitnii** [comment]
@TabeaHe , I ahve added title, description and image for all meta tag groups for all pages (standard, google, twitter). You can edit them in MD files here https://share.cleanshot.com/CjFqHGJ3 . here it is on deployed website (please, clear cache before checking): https://share.cleanshot.com/pb4mLpzQ

Please, let me know, if you will face any issues

**Comment by MaksymOsovitnii** [comment]
@TabeaHe , the same done for DE website + deployed. You can check.

**Comment by TabeaHe** [comment]
@MaksymOsovitnii Thanks! It works well.
