### ISSUE TITLE
pull request #127

### ISSUE THREAD

**Issue by TabeaHe** [Blueshoe/website#131]
Please check pull request #127 . Why is there a space between the "8" and "9" in the phone number?

**Comment by MaksymOsovitnii** [comment]
@TabeaHe , this change was done by Schille. Should I change it back?

**Comment by TabeaHe** [comment]
@MaksymOsovitnii no, please don't change it back. We just don't understand why there is a space between the "8" and the "9" 
![image](https://github.com/Blueshoe/website/assets/106660869/a22571a4-247a-4686-9ba1-18650abf64d4)

Here there is no space
![image](https://github.com/Blueshoe/website/assets/106660869/3c9963a8-371a-4224-aa67-6332dca63c67)

**Comment by Schille** [comment]
@MaksymOsovitnii Please have a look at the source. Maybe I am wrong, but I don't see no space between 8 an 9 (?).

**Comment by MaksymOsovitnii** [comment]
@Schille @TabeaHe Got it, will check and will be back to you

**Comment by MaksymOsovitnii** [comment]
@Schille @TabeaHe , it seems that all is good? Screenshots from both versions are below:
![image](https://github.com/Blueshoe/website/assets/45031013/e9382f27-ce3a-4fdb-83a0-5cd8a3f6343b)
![image](https://github.com/Blueshoe/website/assets/45031013/831e6b2f-eb7a-4c58-8bb2-3b06c4ca3c94)

Where I can find it?

**Comment by MaksymOsovitnii** [comment]
@TabeaHe , I will be waiting for your reply! Thank you

**Comment by TabeaHe** [comment]
@MaksymOsovitnii We wanted to insert some space to make it easier to read the number. But in the end there was a space between 8 and 9 which shouldn't be there

**Comment by MaksymOsovitnii** [comment]
@TabeaHe , ok, now it is clear. Because I didnt understand the task and thought that for some reason in my version is an extra space between 8 and 9. I will check pull request and will make these spaces as Schille wanted and will check that there will be no additional space between 8 and 9.

**Comment by TabeaHe** [comment]
@MaksymOsovitnii perfect! Thank you!

**Comment by MaksymOsovitnii** [comment]
@TabeaHe , how it should look like with spaces on DE version?

**Comment by MaksymOsovitnii** [comment]
@TabeaHe , will be waiting for your reply to update DE version

**Comment by TabeaHe** [comment]
@MaksymOsovitnii I realized that we changed the form of the number in the English website in two different ways. I'm checking which one we will take and come back to you.

**Comment by MaksymOsovitnii** [comment]
@TabeaHe , sure. Let me correct number formats for both version, I will update them

**Comment by TabeaHe** [comment]
@MaksymOsovitnii It should be +49 89 95 45 94 230 in both versions.

**Comment by MaksymOsovitnii** [comment]
@TabeaHe , done on DE version too. Please, check.
