### ISSUE TITLE
Button doesn't work

### ISSUE THREAD

**Issue by TabeaHe** [Blueshoe/website#132]
Why does the button not work? #128

**Comment by MaksymOsovitnii** [comment]
@TabeaHe , you should use GlobalButton component outside of GlobalParagraph component, as GlobalParagraph does not have slots to insert Components. The correct example is below. Try please

:::GlobalParagraph
Let us know if you have any questions, feedback or maybe things we should consider to change. Thank you very much.
:::

:::GlobalButton{:url="/contact" :label="Contact us" :color="blue"}
:::

**Comment by TabeaHe** [comment]
@MaksymOsovitnii thank you. That worked well.
