### ISSUE TITLE
link opt-out cookie

### ISSUE THREAD

**Issue by TabeaHe** [Blueshoe/website#143]
I tried to adapt a link in the legal notice, because it didn't work (unikube.io was inlcuded in the link). You can see what I tried to change here https://github.com/Blueshoe/website/pull/142

It's about this section: You can prevent Google Analytics from collecting data by clicking on the following link. An opt-out cookie is set which prevents the future collection of your data when you visit this website: Deactivate Google Analytics.

How much time would you need to solve that? On the German website the link is entirely missing.

**Comment by MaksymOsovitnii** [comment]
@TabeaHe , I do not understand the task. Can you please explain what should be done and what is the expected result?

**Comment by TabeaHe** [comment]
@MaksymOsovitnii I will make a short explanation viedeo for you on Monday

**Comment by MaksymOsovitnii** [comment]
@TabeaHe , thank you

**Comment by TabeaHe** [comment]
Hey @MaksymOsovitnii , I recorded a Loom about that opt-out issue on our website. Could you please take a look at https://www.loom.com/share/1c0a3d28c6804160940f3f98964977e2?src=composer? I would appreciate your input. Thanks!

**Comment by MaksymOsovitnii** [comment]
@TabeaHe 
I have done it, it took 2 hours, as not only the link, but also the script doing this logic should be added. Will deploy today with other fixes and let you know.

**Comment by MaksymOsovitnii** [comment]
@TabeaHe , done, here is a demo: https://share.cleanshot.com/jMz6srNd

Please, let me know if this works

**Comment by TabeaHe** [comment]
@MaksymOsovitnii it works. Thanks! Could you please do the same for the DE version?

**Comment by MaksymOsovitnii** [comment]
@TabeaHe , I should replace this link https://share.cleanshot.com/y3vBlhhk? What text should I use for the link?

**Comment by TabeaHe** [comment]
@MaksymOsovitnii The text is already there. It's the link, that is missing: 
![image](https://github.com/Blueshoe/website/assets/106660869/ee5217b1-a9b6-41c0-aa41-69b879b11dec)

**Comment by MaksymOsovitnii** [comment]
@TabeaHe , ok, sure, will deploy today and let you know.

**Comment by MaksymOsovitnii** [comment]
@TabeaHe this text is ok for confirmation to user?

Sie haben sich erfolgreich abgemeldet. Google Analytics wird keine Daten mehr über Ihre Besuche auf dieser Website erfassen.

**Comment by TabeaHe** [comment]
@MaksymOsovitnii yes, that's fine.

**Comment by MaksymOsovitnii** [comment]
@TabeaHe , done, please check: https://www.blueshoe.de/impressum/

**Comment by TabeaHe** [comment]
@MaksymOsovitnii That works. Thank you!
