### ISSUE TITLE
API page: "How can API devevlopment benefit your business?" is not visible

### ISSUE THREAD

**Issue by TabeaHe** [Blueshoe/website#147]
Hey @MaksymOsovitnii , could you please take a look at this Loom https://www.loom.com/share/e89a7edf149e488d8e998e529fdb9f06?src=composer? 

Link to the PR: https://github.com/Blueshoe/website/pull/137

Please add a short note for the estimated time you will need to solve a ticket at each ticket and track the time in YouTrack.

**Comment by MaksymOsovitnii** [comment]
@TabeaHe , do we have these tasks (from GitHub) in YouTrack? As I'm working only on one project in YouTrack and I don't think I have permissions and understanding how to create these tasks there and track time correctly for you reporting

Also what is the process?
I should estimate and wait for estimates approval for each task? What if task takes longer than estimated?

**Comment by Truthans** [comment]
@MaksymOsovitnii what would be great is, if you do work for the Blueshoe website, if you could track your times in clockify, not YouTrack. In Clockify just choose the project "[BS] Website" and the task "[BS Website] Development".
Ideally all your work for us is tracked in Clockify. If you ever don't know where to track something to, just contact me.

The time estimations are an indication. It's clear, that you will mostly not hit the exact timing as estimated. However, these are important for us to have some sort of control over our prospective spending, especially as it can be hard for a non developer to estimate when something takes long.

However, if you make an estimation and during implementation realize, that it will take you far longer than anticipated, it would be great, if you could simply go back to the Github issue and update your estimation for further approval.

But as a general agreement we could make, we could say that any task that takes less than two hours can be immediately started by you without prior approval.

Does that all make sense?

**Comment by MaksymOsovitnii** [comment]
@Truthans , Hannes, sure.

@TabeaHe @Truthans 
- I will track all tasks using Clockify (I was not doing it before)
- I will estimate my work and update estimates here
- I will close fats tasks under 2h without estimation, but with tracking them in Clockify

Thank you

**Comment by MaksymOsovitnii** [comment]
@TabeaHe , please check this small video: https://share.cleanshot.com/4X3RcsDy
I hope it helps

**Comment by TabeaHe** [comment]
@MaksymOsovitnii Thanks for your help! Please have a look at the video https://www.loom.com/share/9066dc3be6014aa0b849bbee101f67ca?sid=4809ec02-8472-42da-ad55-731167509a0d

**Comment by MaksymOsovitnii** [comment]
@TabeaHe , But on the video you are showing another part of the page, not the component with cards.
https://share.cleanshot.com/NkrccVkC

**Comment by TabeaHe** [comment]
@MaksymOsovitnii Yes, because part of my problem is that "How can API development benefit my business?" and the cards are not visible. They vanish when I scroll down.

**Comment by TabeaHe** [comment]
@MaksymOsovitnii I mad another video for you showing that the cards disapear "just like that" https://www.loom.com/share/1aac5a17d3bc4e37b9f67c95d6ef6d9d?sid=4b9145f5-482a-4039-a90e-f697390c3f17

**Comment by MaksymOsovitnii** [comment]
@TabeaHe , got it but cant reproduce. 
Lets try to fix issue, we have, maybe it causes this. This components expects in images array object with image and alt text for each card and now it is throwing the issue that the third one do not have an image object + it impacts on UI behaviour. https://share.cleanshot.com/p85FSvXt . After checking please let mew know if the issue still exists.

replace 
```
:::GlobalSliderWithImageSection{:numberCards=3 :bg="bg-white" :imagePosition="right" :images='[{"src": "/img/services/cloud_native_development.svg", "alt": "cloud native development"}, {"src": "/img/services/cloud_native_development.svg", "alt": "cloud native development"}]' :dotColor="black" data-title="How can API development benefit my business?"}
```

with 
```
:::GlobalSliderWithImageSection{:numberCards=3 :bg="bg-white" :imagePosition="right" :images='[{"src": "/img/services/cloud_native_development.svg", "alt": "cloud native development"}, {"src": "/img/services/cloud_native_development.svg", "alt": "cloud native development"},{"src": "/img/services/cloud_native_development.svg", "alt": "cloud native development"}]' :dotColor="black" data-title="How can API development benefit my business?"}
```

**Comment by MaksymOsovitnii** [comment]
@TabeaHe , did it help you?

**Comment by TabeaHe** [comment]
@MaksymOsovitnii Yes, thank you. It works well.
